# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170309_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('es_publico', models.BooleanField()),
                ('localizacion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('creado_a', models.DateTimeField(auto_now_add=True)),
                ('actualizado_a', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellidos', models.CharField(max_length=200)),
                ('creado_a', models.DateTimeField(auto_now_add=True)),
                ('actualizado_a', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito', to='events.Evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
