# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170309_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['creado_a'], 'verbose_name_plural': 'inscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set([('nombre_apellidos', 'evento')]),
        ),
    ]
