# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170309_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='web',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='correo',
            field=models.EmailField(default='a@a.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nif',
            field=models.CharField(default='00000000a', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set([('nif', 'evento')]),
        ),
    ]
