# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170309_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='maximo_inscripcion',
            field=models.IntegerField(default=50, help_text='Número máximo de inscripciones permitidas'),
            preserve_default=False,
        ),
    ]
